name: IaC Kubernetes cluster
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
  workflow_dispatch:
    branches:
    - main
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: main-dev.bicep main-prod.bicep
      - run: ls
      - run: cat main-dev.json
      - run: cat main-prod.json
      - name: Publish Artifacts dev
        uses: actions/upload-artifact@v2
        with:
          name: main-dev
          path: main-dev.json
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main-prod
          path: main-prod.json
  deployDevelopment:
    needs: build
    name: Deploy to development
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts dev
      uses: actions/download-artifact@v2
      with:
        name: main-dev
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: get subs
      id: subs
      run: |
        SUBID=$(az account show --query id --output tsv)
        echo "::set-output name=SUBID::${SUBID}"
    - name: Test
      run: echo "${{ steps.subs.outputs.subid }}"
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ steps.subs.outputs.subid }}
        region: westeurope
        template: main-dev.json
  DeployProduction:
    needs: deployDevelopment
    name: Deploy to production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: main-prod
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: get subs
      id: subs
      run: |
        SUBID=$(az account show --query id --output tsv)
        echo "::set-output name=SUBID::${SUBID}"
    - name: Test
      run: echo "${{ steps.subs.outputs.subid }}"
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ steps.subs.outputs.subid }}
        region: westeurope
        template: main-prod.json
